# Generated by Django 4.2.5 on 2023-09-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moje_konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uzytkownika', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uzytkownika', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=28)),
            ],
        ),
    ]
