# Generated by Django 4.2.5 on 2023-09-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_moje_konto_rejestracja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moje_konto',
        ),
        migrations.DeleteModel(
            name='Rejestracja',
        ),
        migrations.RemoveField(
            model_name='logowanie',
            name='email',
        ),
        migrations.AlterField(
            model_name='logowanie',
            name='haslo',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='logowanie',
            name='nazwa_uzytkownika',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
