# Generated by Django 4.2.5 on 2023-09-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pokoj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc', models.TextField(default='')),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pokoj')),
            ],
        ),
    ]
