# Generated by Django 4.2.5 on 2023-09-28 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_czat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='czat',
            old_name='wiadomosc',
            new_name='czat',
        ),
        migrations.AddField(
            model_name='czat',
            name='stworzono',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-28T10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='czat',
            name='uzytkownik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='czat',
            name='pokoj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='czaty', to='base.pokoj'),
        ),
    ]
